### PR TITLE
Prevent RLE data in corrupt .tga from overflowing the buffer

### LINKED ISSUE #1251: segmentation fault to al_load_bitmap
Hi ,
I found an error while learning the exmple example.
system info:
ubuntu 20.02 TLS
clang 11
comit:03ab10df438860c7c17cf427e3282027d913d93f

```bash
$ ./ex_bitmap crash
```

[crash.zip](https://github.com/liballeg/allegro5/files/6615102/crash.zip)

gdb info
```bash
Program received signal SIGSEGV, Segmentation fault.
[----------------------------------registers-----------------------------------]
RAX: 0xff82ff82ff82ff82 
RBX: 0x0 
RCX: 0x15d5 
RDX: 0x1 
RSI: 0x7fffffffdc7f --> 0x10ff 
RDI: 0x61de50 --> 0xff82ff82ff82ff82 
RBP: 0x61ddf0 --> 0xff82ff8200000000 
RSP: 0x7fffffffdc70 --> 0x61f8b0 --> 0x0 
RIP: 0x7ffff7e70fda (<al_fgetc+170>:	call   QWORD PTR [rax+0x10])
R8 : 0x7d ('}')
R9 : 0x61ddf0 --> 0xff82ff8200000000 
R10: 0x0 
R11: 0x7ffff766cbe0 --> 0x620270 --> 0x0 
R12: 0x61de50 --> 0xff82ff82ff82ff82 
R13: 0x40a180 --> 0x40a210 --> 0x100000102000100 
R14: 0x0 
R15: 0x0
EFLAGS: 0x10246 (carry PARITY adjust ZERO sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff7e70fd0 <al_fgetc+160>:	mov    edx,0x1
   0x7ffff7e70fd5 <al_fgetc+165>:	xor    ebx,ebx
   0x7ffff7e70fd7 <al_fgetc+167>:	mov    rax,QWORD PTR [rdi]
=> 0x7ffff7e70fda <al_fgetc+170>:	call   QWORD PTR [rax+0x10]
   0x7ffff7e70fdd <al_fgetc+173>:	add    rax,rbx
   0x7ffff7e70fe0 <al_fgetc+176>:	cmp    rax,0x1
   0x7ffff7e70fe4 <al_fgetc+180>:	movzx  ecx,BYTE PTR [rsp+0xf]
   0x7ffff7e70fe9 <al_fgetc+185>:	mov    eax,0xffffffff
Guessed arguments:
arg[0]: 0x61de50 --> 0xff82ff82ff82ff82 
arg[1]: 0x7fffffffdc7f --> 0x10ff 
arg[2]: 0x1 
arg[3]: 0x15d5 
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffdc70 --> 0x61f8b0 --> 0x0 
0008| 0x7fffffffdc78 --> 0xff82000000000002 
0016| 0x7fffffffdc80 --> 0x10 
0024| 0x7fffffffdc88 --> 0x7ffff7fb98e8 (<_al_load_tga_f+3784>:	mov    ebx,eax)
0032| 0x7fffffffdc90 --> 0x7fff00100958 
0040| 0x7fffffffdc98 --> 0x61ddf0 --> 0xff82ff8200000000 
0048| 0x7fffffffdca0 --> 0xf0040a180 
0056| 0x7fffffffdca8 --> 0x10 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
0x00007ffff7e70fda in al_fread (f=0x61de50, ptr=0x7fffffffdc7f, size=<optimized out>) at /home/hh/Downloads/allegro5/src/file.c:116
116	      return bytes_ungetc + f->vtable->fi_fread(f, cptr, size);
```

```bash

#0  0x00007ffff7e70fda in al_fread (f=0x61de50, ptr=0x7fffffffdc7f, size=<optimized out>) at /home/hh/Downloads/allegro5/src/file.c:116
#1  al_fgetc (f=f@entry=0x61de50) at /home/hh/Downloads/allegro5/src/file.c:229
#2  0x00007ffff7fb98e8 in rle_tga_read16 (b=0x61ddf0, w=<optimized out>, f=<optimized out>) at /home/hh/Downloads/allegro5/addons/image/tga.c:212
#3  _al_load_tga_f (f=f@entry=0x61de50, flags=flags@entry=0x0) at /home/hh/Downloads/allegro5/addons/image/tga.c:467
#4  0x00007ffff7fba51f in _al_load_tga (filename=0x7fffffffe595 "crash", 
    flags=0x0) at /home/hh/Downloads/allegro5/addons/image/tga.c:565
#5  0x00007ffff7e22753 in al_load_bitmap_flags (
    filename=filename@entry=0x7fffffffe595 "crash", flags=0xffffdc7f)
    at /home/hh/Downloads/allegro5/src/bitmap_io.c:207
#6  0x00007ffff7e22622 in al_load_bitmap (
    filename=filename@entry=0x7fffffffe595 "crash")
    at /home/hh/Downloads/allegro5/src/bitmap_io.c:184
#7  0x0000000000403688 in main (argc=argc@entry=0x2, argv=argv@entry=0x7fffffffe2d8) at /home/hh/Downloads/allegro5/examples/ex_bitmap.c:77
#8  0x00007ffff74a80b3 in __libc_start_main (main=0x4035a0 <main>, argc=0x2, argv=0x7fffffffe2d8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe2c8) at ../csu/libc-start.c:308
#9  0x00000000004032fe in _start ()
```

### PR DESCRIPTION
**Pull request by pedro-w**
Also masked out the 1-bit A value from a 15-bit image; this could
cause the bounds of `_al_rgb_scale_5[]` to be exceeded.

**PLEASE REVIEW** as the TGA loader is complicated (may be possible to simplify with a more extensive re-write)

Fixes #1251

### CODE REVIEW

File: addons/image/tga.c [hunk 1]
```diff
@@ -320,7 +338,9 @@ ALLEGRO_BITMAP *_al_load_tga_f(ALLEGRO_FILE *f, int flags)
 
       case 1:
          /* paletted image */
-         if ((palette_type != 1) || (bpp != 8)) {
+         /* Only support 8 bit palettes (up to 256 entries) though in principle the file format could have more(?)*/
+         if ((palette_type != 1) || (bpp != 8) || (palette_start + palette_colors) > 256) {
+            ALLEGRO_ERROR("Invalid palette/image/bpp combination %d/%d/%d.\n", image_type, palette_type, bpp);
```
Comment (SiegeLord) [inline addons/image/tga.c:343]: The values don't correspond to the description (e.g. you could say 'Invalid image/palette/bpp' instead).

**Review by SiegeLord — CHANGES_REQUESTED** [review]
This looks great, thanks! Just one minor issue in the comments.

File: addons/image/tga.c (hunk 1 above)
Comment (pedro-w) [reply addons/image/tga.c:343]: Good point -  I just copied it from line 357 / line 365 actually (`git blame` knows who wrote those lines :wink: ) - I'll fix them all up the same.

Comment (SiegeLord) [reply addons/image/tga.c:343]: Whoops! Thanks!

Comment (pedro-w) [reply addons/image/tga.c]: done!

**Review by SiegeLord — APPROVED** [review]

**Comment by SiegeLord** [comment]
This looks awesome. I looked over it, and it looks good; all the tests pass, sounds like it's all good. We should add the testcases that motivated this, but we can do that later.
